//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseManager.Presentation {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExpenseManagerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ExpenseManagerResource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpenseManager.Presentation.ExpenseManagerResource", typeof(ExpenseManagerResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Access denied.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Access to user was successfully granted.
        /// </summary>
        public static string AccessGranted {
            get {
                return ResourceManager.GetString("AccessGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Account successfully created.
        /// </summary>
        public static string AccountCreated {
            get {
                return ResourceManager.GetString("AccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User with given email already has an account.
        /// </summary>
        public static string AlreadyHasAccount {
            get {
                return ResourceManager.GetString("AlreadyHasAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User with given email does not exist.
        /// </summary>
        public static string EmailDoesntExist {
            get {
                return ResourceManager.GetString("EmailDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error from external provider.
        /// </summary>
        public static string ErrorFromExteralProvider {
            get {
                return ResourceManager.GetString("ErrorFromExteralProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expense successfully created.
        /// </summary>
        public static string ExpenseCreated {
            get {
                return ResourceManager.GetString("ExpenseCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expense successfully deleted.
        /// </summary>
        public static string ExpenseDeleted {
            get {
                return ResourceManager.GetString("ExpenseDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expense could not be deleted, it probably doesn&apos;t exist..
        /// </summary>
        public static string ExpenseNotDeleted {
            get {
                return ResourceManager.GetString("ExpenseNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The external login was added..
        /// </summary>
        public static string ExternalLoginAdded {
            get {
                return ResourceManager.GetString("ExternalLoginAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The external login was removed..
        /// </summary>
        public static string ExternalLoginRemoved {
            get {
                return ResourceManager.GetString("ExternalLoginRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid code..
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid input data.
        /// </summary>
        public static string InvalidInputData {
            get {
                return ResourceManager.GetString("InvalidInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string PasswordSet {
            get {
                return ResourceManager.GetString("PasswordSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Your phone number was added..
        /// </summary>
        public static string PhoneNumberAdded {
            get {
                return ResourceManager.GetString("PhoneNumberAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Your phone number was removed..
        /// </summary>
        public static string PhoneNumberRemoved {
            get {
                return ResourceManager.GetString("PhoneNumberRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Plan was successfully created.
        /// </summary>
        public static string PlanCreated {
            get {
                return ResourceManager.GetString("PlanCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Plan successfully deleted.
        /// </summary>
        public static string PlanDeleted {
            get {
                return ResourceManager.GetString("PlanDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Plan could not be deleted, it probably doesn&apos;t exist..
        /// </summary>
        public static string PlanNotDeleted {
            get {
                return ResourceManager.GetString("PlanNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Your two-factor authentication provider has been set..
        /// </summary>
        public static string TwoFactorAuthProviderSet {
            get {
                return ResourceManager.GetString("TwoFactorAuthProviderSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unknown error occured.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You already have an account you cannot create new one.
        /// </summary>
        public static string YouHaveAccount {
            get {
                return ResourceManager.GetString("YouHaveAccount", resourceCulture);
            }
        }
    }
}
